# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
